### ISSUE TITLE
Music not playing

### ISSUE THREAD

**Issue by MariussJS** [twlite/music-bot#6]
I have been using the bot on my own server for a long time to use it with my friends, but now it gives this error

```
ERR_NO_RESULT [Error]: [ERR_NO_RESULT] Could not extract stream for this track

Error: Failed to parse data from webpage. (TypeError: Cannot read properties of undefined (reading 'split'))
    at C:\Users\discordmusicbot\Desktop\MariusMusic\node_modules\.pnpm\youtube-ext@1.1.16\node_modules\youtube-ext\dist\videoInfo.js:52:15
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\discordmusicbot\Desktop\MariusMusic\node_modules\.pnpm\youtube-ext@1.1.16\node_modules\youtube-ext\dist\videoInfo.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Proxy.<anonymous> (C:\Users\discordmusicbot\Desktop\MariusMusic\node_modules\.pnpm\discord-player@6.6.10_@discord-player+extractor@4.4.7\node_modules\discord-player\dist\index.js:324:25)
    at #throw (C:\Users\discordmusicbot\Desktop\MariusMusic\node_modules\.pnpm\discord-player@6.6.10_@discord-player+extractor@4.4.7\node_modules\discord-player\dist\index.js:2900:80)      
    at _GuildQueuePlayerNode.play (C:\Users\discordmusicbot\Desktop\MariusMusic\node_modules\.pnpm\discord-player@6.6.10_@discord-player+extractor@4.4.7\node_modules\discord-player\dist\index.js:2802:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _Player.play (C:\Users\discordmusicbot\Desktop\MariusMusic\node_modules\.pnpm\discord-player@6.6.10_@discord-player+extractor@4.4.7\node_modules\discord-player\dist\index.js:5654:9)
    at async Object.run (file:///C:/Users/discordmusicbot/Desktop/MariusMusic/apps/music-bot/dist/commands/music/play.js?t=1720391717491:38:41) Track { lots of information }

[Player] [AsyncQueue] Releasing an entry from the queue...
(node:8884) [UnhandledEventsWarning] Warning: No event listener found for event "playerError". Events "error", "playerError" must have event listeners.
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by twlite** [comment]
should be fixed, if it does not work, try using [discord-player-youtubei](https://npm.im/discord-player/youtubei) package
